[package]
name = "uuid-lite"
version = "1.1.2"
edition = "2024"
description = "A minimal random (v4) UUID generator."
license = "MIT"

[lib]
name = "uuid_lite"
path = "src/lib.rs"

[dependencies]
getrandom = "0.4"

[features]
01RIH4fRi60CU8GSj_Jm4VGab_i6ZKD9izoEs_hg7sa30 = []
02ZzjNig0-NamH6dmcQA6Ma38ou4t3Q2Mn4btqzNGOH4Q = []
03sZHU2DXsbW8mhGHXwgbzEX8ou4t3Q2Mn4btqzNGOH4Q = []
04QxAXE2THF6Jg-6EK4Rad7X8ou4t3Q2Mn4btqzNGOH4Q = []
05yOIpD-Z30ypcXe7VDf3cin8ou4t3Q2Mn4btqzNGOH4Q = []
06vWBmEvhOAUrJYCMMwohvCX8ou4t3Q2Mn4btqzNGOH4Q = []
07wuOc8bkV58yDfgNCAWqZ238ou4t3Q2Mn4btqzNGOH4Q = []
08z0vn-gseyhVCrG9GwvkW7n8ou4t3Q2Mn4btqzNGOH4Q = []
09c5mBoUShXT5AVZTI9UBsow = []
c1C8PqUPuXtJcHftvVYMnpvCDFnjoNswRGqxMD_GMS0tgzp9QbWBhGZycY7Y87doQpVJWGZWDTJShvLx_3WS0Ss80SHeeID9MPjtQjpgS7deSWDqyNkl4RRoSNQiVgDrvv = []
